### ISSUE TITLE
ELF sample with Big Endian Data Encoding

### ISSUE THREAD

**Issue by PAX523** [JonathanSalwan/binary-samples#10]
Hallo.

Thanks a lot for the provided ELF samples! Is there also a sample where `Elf_Ehdr.e_ident[EI_DATA]` is set to `ELFDATA2MSB` (Big Endian)?

If not, could you provide such a binary sample to me?

Cheers

PAX

**Comment by JonathanSalwan** [comment]
Yes: `elf-Linux-SparcV8-bash`, `elf-Linux-PowerPC-bash`, etc.
