### ISSUE TITLE
licensing?

### ISSUE THREAD

**Issue by psifertex** [JonathanSalwan/binary-samples#6]
Any chance of updating the licensing info for the repository? It looks like everything is GPLv3 from a quick look through the files, but it'd be nice to be explicit. Happy to issue a pull request if you prefer that. 

For reference, I'd like to submodule this repo into another repository that is MIT licensed so I wanted the license file just to make clear the distinction between the two.

**Comment by JonathanSalwan** [comment]
Well, there is currently no licence into this repository. However, I don't know if a licence of a compiled binary must be the same than its source. I'm talking about the ELF binaries  - bash and libc which are GPL and Macho which are BSD...

Anyway, I think you can fork this repository and choose your own licence :). However, I'm interested if you have answers about my previous questions. If we can put the MIT or BSD licence go ahead and send me a pull request :)

Cheers,

**Comment by psifertex** [comment]
Pretty sure the compiled binaries need to have a license compatible with the source. Not necessarily the same, but not incompatible. IE, can't suddenly close-source any of them, or go from GPL->MIT (though the reverse is fine).

The repository as a whole doesn't have to have a license, it just makes things a bit easier if there is some documentation instead of forcing someone to look at each binary. I'll submit a PR describing the licenses for each individual file so it's at least documented. if you want to put another license on everything, you could with GPLv3.

Of course, IANAL, so take that for what it's worth. :-)

**Comment by psifertex** [comment]
Also, ok if I mark everything inside `anti-disassembler` as MIT since that looks like your code?

**Comment by JonathanSalwan** [comment]
Le 5 juin 2016 23:45, "Jordan" <notifications@github.com> a écrit :
>
> Also, ok if I mark everything inside anti-disassembler as MIT since that
looks like your code?

It's not my code, cc @perror.

**Comment by perror** [comment]
@psifertex 
Concerning the GPLed code, it surely must remain GPL as MIT is more permissive than GPL.

Concerning the toy examples for anti-disassembly, well, I consider this code as "public domain" and it should be kept as such. If you put an MIT license upon it, it will add a copyright on it... which will just break the thing.

Anyway, what is the gain of putting a restrictive license on a program which is, at most, 10 lines long and that will probably stay like this as it is just a benchmark?

Really, I don't see your point here... You must have a lot of spare time (which is not my case, sorry).

**Comment by psifertex** [comment]
@perror I agree about GPL/MIT -- that's exactly what I said above about GPL -> MIT couldn't happen, but MIT -> GPL could. 

Might I suggest an explicit note of public domain? Unfortunately the way copyright works in the US at least, not putting any copyright notice does /not/ make it public domain by default but rather fully protected. :-(

I have very little spare time  -- I'm just very careful with licensing as I'd like to include this repository in my company's public repository and we've already seen two occasions where a repository claimed a particular license but when we double checked, found differently licensed source intermingled internally.

**Comment by perror** [comment]
@psifertex Yes, we should add something stating that the code is totally free of use... The problem is that I cannot find a suitable text stating that there is no copyright on this code... or maybe I missed it.

By default, the [Github policy for unlicensed code](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) is the following:

> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

> Even if this is what you intend, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository within the GitHub site.

> If you want others to use, copy, modify, or contribute back to your project, we strongly encourage you to include an open source license.

So, the simplest way to get out this is simply to take the default license given by Github (because I did not find any convincing text stating that the code is in public domain). 

But, between you and me, yes, take this code and do what you want with it. It is small, quick and dirty, and I am not even sure that I did it all by my side without getting inspired from other codes.

**Comment by psifertex** [comment]
There's are public domain dedications out there. Creative Commons has CC0 and there's also the unlicense (unlicense.org) specifically for software. I'll make a PR and see what you guys think. Thanks.

**Comment by JonathanSalwan** [comment]
> I'll make a PR and see what you guys think.

Thanks.

**Comment by psifertex** [comment]
Thanks -- sorry I forgot to issue the PR. :-/

This works for me.
