### ISSUE TITLE
Scope of project: bytecode?

### ISSUE THREAD

**Issue by FireyFly** [JonathanSalwan/binary-samples#7]
I'm curious if it would be interesting to expand the scope of this collection to include both native binaries as well as samples of bytecode formats, seeing as how similar kinds of analysis tools are useful in both cases (disassembler, decompiler, control flow analysis etc). I guess it could be a slippery slope though what one considers to be a bytecode format..

Kind of regardless of scope, it might be useful to categorise the samples inside subdirectories instead of keeping them in the repository root.

**Comment by JonathanSalwan** [comment]
Sounds good to me. Let's go ahead with a PR :)
